name: DeployCloudKatana

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          azure_user: ${{ secrets.AZURE_USER }}
          azure_password: ${{ secrets.AZURE_PASSWORD }}
          inlineScript: |
            $pass = ConvertTo-SecureString "$env:AZURE_USER" -AsPlainText -Force
            $creds = New-Object PSCredential ("$env:AZURE_PASSWORD", $pass)
            Connect-AzAccount -Credential $creds 
            
            New-AzResourceGroupDeployment -ResourceGroupName 'SOC-CK-Play5' `
                                          -TemplateFile "$env:GITHUB_WORKSPACE/main.template.json" `
                                          -fileLocation "https://$storageName.blob.core.windows.net/template-files" `
                                          -resourceNamePrefix 'SOC' `
                                          -resourceNameSuffix 'Play5' `
                                          -gaUserName "$env:AZURE_USER" `
                                          -gaPassword $pass `
                                          -githubRepo $env:GITHUB_REPOSITORY `
                                          -assignAppRoleToUser "$env:AZURE_USER" `
                                          -Verbose
          azPSVersion: 'latest'
