name: DeployCloudKatana

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    environment: Dev
    env:
      AZURE_USER: '${{ secrets.AZURE_USER }}'
      AZURE_PASSWORD: '${{ secrets.AZURE_PASSWORD }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Deployment
        shell: pwsh
        run: |
              Install-Module Az -Force -Confirm:$false
              $pass = ConvertTo-SecureString $env:AZURE_USER -AsPlainText -Force
              $creds = New-Object PSCredential ($env:AZURE_PASSWORD, $pass)
              Connect-AzAccount -Credential $creds 

              New-AzResourceGroupDeployment -ResourceGroupName 'SOC-CK-Play5' `
                                            -TemplateFile "$env:GITHUB_WORKSPACE/main.template.json" `
                                            -fileLocation "https://$storageName.blob.core.windows.net/template-files" `
                                            -resourceNamePrefix 'SOC' `
                                            -resourceNameSuffix 'Play5' `
                                            -gaUserName $env:AZURE_USER `
                                            -gaPassword $pass `
                                            -githubRepo $env:GITHUB_REPOSITORY `
                                            -assignAppRoleToUser $env:AZURE_USER `
                                            -Verbose
