name: DeployCloudKatana

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    environment: Dev
    env:
      AZURE_USER: '${{ secrets.AZURE_USER }}'
      AZURE_PASSWORD: '${{ secrets.AZURE_PASSWORD }}'
      RESOURCE_NAME_PREFIX: 'SOC'
      RESOURCE_NAME_SUFFIX: 'Play5'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.DEPLOYMENT_SPN }}
          enable-AzPSSession: true
      - name: Deploy resource group
        uses: Azure/powershell@v1
        with:
          inlineScript:  |
            if(!(Get-AzResourceGroup|where ResourceGroupName -eq "$env:RESOURCE_NAME_PREFIX-CK-$env:RESOURCE_NAME_SUFFIX"))
            {
              New-AzResourceGroup -Name "$env:RESOURCE_NAME_PREFIX-CK-$env:RESOURCE_NAME_SUFFIX" -Location eastus
            }
          azPSVersion: "latest"
      - name: Run deployment
        uses: Azure/powershell@v1
        with:
          inlineScript:  |
              $pass = ConvertTo-SecureString $env:AZURE_PASSWORD -AsPlainText -Force

              New-AzResourceGroupDeployment -ResourceGroupName "$env:RESOURCE_NAME_PREFIX-CK-$env:RESOURCE_NAME_SUFFIX" `
                                            -TemplateFile "$env:GITHUB_WORKSPACE/main.template.json" `
                                            -artifactsLocation "https://raw.githubusercontent.com/$env:GITHUB_REPOSITORY/master" `
                                            -resourceNamePrefix $env:RESOURCE_NAME_PREFIX `
                                            -resourceNameSuffix $env:RESOURCE_NAME_SUFFIX `
                                            -gaUserName $env:AZURE_USER `
                                            -gaPassword $pass `
                                            -githubRepo $env:GITHUB_REPOSITORY `
                                            -assignAppRoleToUser $env:AZURE_USER `
                                            -Verbose
          azPSVersion: "latest"
